@startuml
!include <C4/C4_Context>

Person(user, 'Пользователь')

System(warm_house, 'Теплый дом', 'Система управления отоплением:\n-  Управление работой отопления \n- Настройка целевых значений')

System_Ext(sensor_device, 'Температурный сенсор', 'Измеряет температуру')

Rel(user, warm_house, 'Управление отоплением, получение данных о температуре')

Rel(warm_house, sensor_device, 'Получение данных от датчиков')

@enduml