@startuml
title ER-диаграмма

skinparam linetype ortho

entity User {
  * userId : NUMBER
  --
  * userId : NUMBER
  * password : VARCHAR (20)
  * email : VARCHAR (30)
  firstName : VARCHAR (20)
  lastName : VARCHAR (20)
}

entity House {
  * houseId : NUMBER
  --
  * houseId : NUMBER
  * userId : NUMBER
  * address : VARCHAR(100)
  displayName : VARCHAR(20)
}

entity Device {
  * deviceId : NUMBER
  --
  * deviceId : NUMBER
  * typeId : NUMBER
  * houseId : NUMBER
  * status : NUMBER
  displayName : VARCHAR(20)
  description : VARCHAR(50)
  workflowId : NUMBER
}

entity DeviceType {
    * typeId : NUMBER
    --
    * typeId : NUMBER
    description : VARCHAR(50)
}

entity TelemetryData {
    * id : NUMBER
    --
    * id : NUMBER
    * deviceId : NUMBER
    * datetime : DATETIME
    * data : JSON
}

entity Workflow {
    * id : NUMBER
    --
    * id : NUMBER
    * houseId : NUMBER
    * sequence  : JSON
    description : VARCHAR (100)
}

House }|--|{ User
Device }|--|| House
DeviceType ||--|{ Device
TelemetryData }|--|| Device
Workflow }|--|{ Device
House |o--|{ Workflow

@enduml